Repository lincoln1883/Appointment-capstone-backend, pull requests merged in 2023-10, with the labels that each got.

#34 Swagger api documentation
  Gemfile
  Gemfile.lock
  config/initializers/rswag_api.rb
  config/initializers/rswag_ui.rb
  config/routes.rb
  spec/swagger_helper.rb
  swagger/v1/swagger.yaml
Labels: documentation

#38 Modifications on reservations and DB
  README.md
  app/controllers/api/v1/reservations_controller.rb
  app/controllers/api/v1/trades_controller.rb
  app/controllers/api/v1/users_controller.rb
  app/models/reservation.rb
  app/models/user.rb
  db/migrate/20230929155755_create_reservations.rb
  db/schema.rb
  db/seeds.rb
  spec/factories/reservation.rb
  spec/models/reservation_spec.rb
  spec/requests/api/v1/reservation_spec.rb
Labels: bug, enhancement

#39 Fixed bugs and Resolved issues along with Enhancement of the APP
  Gemfile.lock
  README.md
  app/controllers/api/v1/reservations_controller.rb
  app/controllers/api/v1/trades_controller.rb
  app/controllers/api/v1/users_controller.rb
  app/models/reservation.rb
  app/models/user.rb
  bin/rails
  bin/rake
  bin/render-build.sh
  bin/setup
  config/application.rb
  config/credentials.yml.enc
  config/database.yml
  config/environments/production.rb
  config/initializers/cors.rb
  config/initializers/devise.rb
  db/migrate/20230929155755_create_reservations.rb
  db/migrate/20231003141524_add_removed_to_trades.rb
  db/schema.rb
  db/seeds.rb
  public/kanban-board-initial.png
  render.yaml
  spec/factories/reservation.rb
  spec/factories/trades.rb
  spec/models/reservation_spec.rb
  spec/requests/api/v1/reservation_spec.rb
  spec/requests/api/v1/trades_spec.rb
  spec/requests/api/v1/users/sessions_controller_spec.rb
  spec/requests/api/v1/users_spec.rb
Labels: bug, documentation, enhancement
